### ISSUE TITLE
Insane stuttering

### ISSUE THREAD

**Issue by Sparkpy** [Goorakh/RiskOfChaos#1]
This mod causes insane stuttering, I tested my ror2 fps with and without the mod:
With Mod: 9fps 99%
Without Mod: 86fps 99%

I assume this has something to do with a lot of repetitive tests being run on each frame or the sleep function being very inefficient for a game, an idea is to try multiprocessing/multithreading the timer and the game (if possible)

Spark#3063 (Contact me on discord if you want/need help with that)

**Comment by Goorakh** [comment]
This is very strange considering literally the only update method (being run each frame) in the entire mod is ![this one with only a few lines](https://github.com/Goorakh/RiskOfChaos/blob/master/RiskOfChaos/EffectHandling/ChaosEffectDispatcher.cs#L85)

Is this an entirely consistent issue? Like does this performance drop happen every single time?

What other mods are you using (if any)?

Please also upload the logfile after starting the game with the mod and getting this performance drop.

And as for multithreading, Unity *really* doesn't like it, and I doubt it would help much since the only update method is very simple.

**Comment by Goorakh** [comment]
Cannot reproduce
