### ISSUE TITLE
[suggestion] a server-side version of the mod

### ISSUE THREAD

**Issue by Deflaktor** [Goorakh/RiskOfChaos#5]
I like the idea and thought of making such a mod myself. But I see that everyone must have this mod installed in order to play in multiplayer. Suggestion would be to make a version of this mod which works purely server-side.

**Comment by Goorakh** [comment]
Originally I did want the mod to be completely serverside, but doing that restricts you to the game's built-in networking, which is pretty good, but not really ideal. Custom rules and communication between clients and server avoids all those restrictions and so can do effectively anything.

I doubt I'll make a server-side only version at this point though since it would require many effects and features to be completely removed. You are free to make your own fork and make a server-only version if you'd like however :)
